Qmk 0.19.12
system76/qmk_firmware pull request #34
Opened 2023-02-24 19:44 UTC by 13r0ck

Rebase onto qmk 0.19.12, will need to be force pushed once approved.

Requires https://github.com/pop-os/keyboard-configurator/pull/156

2023-02-28 21:16 UTC, 13r0ck commented
This currently doesn't work

2023-03-06 17:05 UTC, 13r0ck commented
@leviport this is now ready for qa review

2023-03-13 23:36 UTC, leviport requested changes
After flashing this updated firmware the "Access Layer #" keys aren't being labeled correctly in the configurator. They still work fine though.
![2023-03-13_17-27-13](https://user-images.githubusercontent.com/13512097/224855086-69857f8e-218b-4ca5-830c-cf8af540316f.png)

After re-mapping them to the Access keys with the configurator, they still work and the labels are displayed in the configurator as expected.

2023-03-14 19:10 UTC, 13r0ck commented
@leviport pop-os/keyboard-configurator#164 should fix that

2023-03-14 20:31 UTC, ids1024 commented
Hm, if `Fn` has changed mapping, how does that impact existing keymap configurations? The firmware update isn't supposed to wipe configuration back to default, right?

2023-03-29 22:06 UTC, jackpot51 approved these changes

2023-03-29 22:35 UTC, merged